[connections.postgresql]
dialect = "postgresql"
host = "db-pgsql-nyc3-27976-do-user-39093605-0.j.db.ondigitalocean.com"
port = "25060"
database = "defaultdb"
username = "doadmin"
password = "AVNS_LZWGGsrwPMKktDl5vfH"